fun main() {
    println("Start: ")
    Day01.all()
    Day02.all()
    Day03.all()
    Day04.all()
    Day05.all()
    Day06.all()
    Day07.all()
    Day08.all()
    Day09.all()
    Day10.all()
    Day11.all()
    println("All done!")
}
